# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM ubuntu:22.04
# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-venv \
    python3-pip \
    curl \
    ca-certificates \
    git \
    build-essential \
    libssl-dev \
 && rm -rf /var/lib/apt/lists/*

# Set workdir
WORKDIR /app

# Copy project files
COPY . /app

# Install Python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Install Foundry toolchain
RUN curl -L https://foundry.paradigm.xyz | bash && \
    ~/.foundry/bin/foundryup

# Add Foundry to PATH
ENV PATH="/root/.foundry/bin:$PATH"

# Ensure run_clean.py is executable
RUN chmod +x run_clean.py

# Default entrypoint
ENTRYPOINT ["python3", "run_clean.py"]
